# Generated by Django 4.2.7 on 2025-11-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1000)),
                ('tipo', models.CharField(choices=[('competicion', 'Competición'), ('entrenamiento', 'Entrenamiento'), ('reunion', 'Reunión'), ('torneo', 'Torneo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('participantes_count', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_publico', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento Deportivo',
                'verbose_name_plural': 'Eventos Deportivos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.eventodeportivo')),
            ],
            options={
                'verbose_name': 'Participante Evento',
                'verbose_name_plural': 'Participantes Eventos',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
