# Generated by Django 4.2.7 on 2025-11-05 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_participacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventodeportivo',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participanteevento',
            unique_together={('usuario', 'evento')},
        ),
        migrations.AddIndex(
            model_name='eventodeportivo',
            index=models.Index(fields=['fecha_inicio'], name='eventos_eve_fecha_i_3aab36_idx'),
        ),
        migrations.AddIndex(
            model_name='eventodeportivo',
            index=models.Index(fields=['organizador'], name='eventos_eve_organiz_209030_idx'),
        ),
    ]
