# Generated by Django 5.2.8 on 2025-11-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_add_entrenamientos'),
        ('publicaciones', '0002_initial'),
    ]

    operations = [
    ]
