# Generated by Django 5.2.8 on 2025-11-14 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_merge_0002_add_entrenamientos_0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesionentrenamiento',
            options={'ordering': ['-inicio'], 'verbose_name': 'Sesión de Entrenamiento', 'verbose_name_plural': 'Sesiones de Entrenamiento'},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_actualizacion',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sesionentrenamiento',
            name='deporte',
            field=models.CharField(choices=[('correr', 'Correr'), ('ciclismo', 'Ciclismo'), ('natacion', 'Natación'), ('gimnasio', 'Gimnasio'), ('yoga', 'Yoga'), ('futbol', 'Fútbol'), ('basquet', 'Básquet'), ('tenis', 'Tenis'), ('boxeo', 'Boxeo'), ('crossfit', 'CrossFit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionentrenamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_entrenamiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
