# Generated by Django 4.2.7 on 2025-11-05 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='seguidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siguiendo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['seguidor'], name='seguimiento_seguido_c8c662_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['seguido'], name='seguimiento_seguido_84f8d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seguimiento',
            unique_together={('seguidor', 'seguido')},
        ),
    ]
